version: '3.8'
services:
  mysql:
    image: mysql:8.0.34
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
        MYSQL_USER: test
        MYSQL_PASSWORD: test
    volumes:
        - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
  postgresql:
    image: postgres:latest
    environment:
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
        POSTGRES_DB: test
    volumes:
        - postgresql:/var/lib/postgresql/data
    ports:
      - 5439:5432
    restart: always

volumes:
    mysql:
    postgresql:
