version: '3.8'
services:
  fastapi:
    build:
      context: python
      dockerfile: Dockerfile
    volumes:
      - ./python:/app
    expose:
      - 8000
    depends_on:
      - mongo
      - elasticsearch
    links:
      - mongo
      - elasticsearch
    env_file:
      - configuration.env

  nginx:
    image: nginx:1.25.1-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi


  mongo:
    image: mongo:latest
    env_file:
      - configuration.env
    volumes:
      - mongodb_data:/data/db
    expose:
      - 27017

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    env_file:
      - configuration.env
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data


volumes:
  mongodb_data: {}
  esdata: {}