version: '3.8'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./python:/app
    expose:
      - 8000
    links:
      - mysql
      - elasticsearch
    env_file:
      - configuration.env

  nginx:
    image: nginx:1.25.1-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi

  telegraf:
    image: arm64v8/telegraf:latest
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
#    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    expose:
      - 8125/udp
      - 8092/udp
      - 8094
    links:
      - influxdb
      - mysql

  influxdb:
    image: arm64v8/influxdb:1.8.10
    env_file: configuration.env
    expose:
        - 8086
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    expose:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

  mysql:
    image: mysql:latest
    restart: always
    env_file:
      - configuration.env
    volumes:
      - mysql_data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    env_file:
      - configuration.env
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data


volumes:
  grafana_data: {}
  influxdb_data: {}
  mysql_data: {}
  esdata: {}